// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface APIResponse<T> {
  success: boolean;
  statusCode: number;
  message: string;
  data: T[];
  token?: string;
}

export interface Role {
  roleId: string;
  name: string;
  description?: string;
}

export interface User {
  staffId:string,
  firstName:string,
  lastName:string,
  email:string
} 